name: geoQMLEnv
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - blas
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - charset-normalizer
  - expat
  - filelock
  - freetype
  - idna
  - jinja2
  - jpeg
  - lcms2
  - lerc
  - libcxx
  - libdeflate
  - libffi
  - libjpeg-turbo
  - libpng
  - libtiff
  - libwebp-base
  - lz4-c
  - markupsafe
  - mpmath
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - pillow
  - pip
  - pysocks
  - python
  - pytorch
  - pyyaml
  - readline
  - requests
  - setuptools
  - sqlite
  - sympy
  - tbb
  - tk
  - torchaudio
  - torchvision
  - typing_extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - annotated-types
    - appdirs
    - autograd
    - autoray
    - cachetools
    - cffi
    - contourpy
    - cryptography
    - cycler
    - dill
    - fonttools
    - fsspec
    - future
    - ibm-cloud-sdk-core
    - ibm-platform-services
    - kiwisolver
    - matplotlib
    - packaging
    - pbr
    - pennylane
    - pennylane-lightning
    - psutil
    - pycparser
    - pydantic
    - pydantic-core
    - pyjwt
    - pylatexenc
    - pyparsing
    - pyspnego
    - python-dateutil
    - qiskit
    - qiskit-aer
    - qiskit-ibm-runtime
    - requests-ntlm
    - rustworkx
    - scipy
    - semantic-version
    - six
    - stevedore
    - symengine
    - toml
    - websocket-client

